export const workItems = [
  {
    id: 1,
    title: 'Vibe Coding',
    slug: 'vibe-coding',
    description: 'Innovative coding projects that blend creativity with technical excellence. Explore cutting-edge web applications and interactive experiences.',
    gifUrl: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 2,
    title: 'UX Case Studies',
    slug: 'ux-case-studies',
    description: 'Deep dive into user experience design processes, research methodologies, and solutions that solve real-world problems.',
    gifUrl: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 3,
    title: 'Designs',
    slug: 'designs',
    description: 'Visual design work spanning brand identity, interfaces, and creative concepts that push boundaries.',
    gifUrl: 'https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const resources = [
  {
    id: 1,
    title: 'Design Systems Guide',
    slug: 'design-systems-guide',
    description: 'Comprehensive guide to building scalable design systems',
    thumbnailUrl: 'https://images.pexels.com/photos/326503/pexels-photo-326503.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 2,
    title: 'Modern CSS Techniques',
    slug: 'modern-css-techniques',
    description: 'Advanced CSS patterns and best practices for 2024',
    thumbnailUrl: 'https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 3,
    title: 'UX Research Methods',
    slug: 'ux-research-methods',
    description: 'Essential user research techniques for designers',
    thumbnailUrl: 'https://images.pexels.com/photos/3184357/pexels-photo-3184357.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 4,
    title: 'Performance Optimization',
    slug: 'performance-optimization',
    description: 'Speed up your web applications with proven strategies',
    thumbnailUrl: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 5,
    title: 'Accessibility Standards',
    slug: 'accessibility-standards',
    description: 'Making the web inclusive for everyone',
    thumbnailUrl: 'https://images.pexels.com/photos/267569/pexels-photo-267569.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
];

export const projects = [
  {
    id: 1,
    title: 'Orchest Ticketing Agent',
    category: 'vibe-coding',
    description: 'AI-powered project management system that turns ideas and conversations into actionable tickets',
    thumbnailUrl: '/thumbnail.png',
    slug: 'Orchest-ticketing-agent',
  },
  {
    id: 2,
    title: 'LeadFlow Find Prospects',
    category: 'vibe-coding',
    description: 'Automate lead discovery and send personalized emails that convert',
    thumbnailUrl: '/lead-thumbnail.png',
    slug: 'LeadFlow-find-prospects',
  },
  {
    id: 4,
    title: 'Smart Applicant Tracking System (ATS)',
    category: 'ux-case-studies',
    description: 'Streamline hiring, manage candidates, and accelerate recruitment with ease.',
    thumbnailUrl: '/ats-thumbnail.png',
    slug: 'smart-applicant-tracking-system',
  },
  {
    id: 3,
    title: 'SEOBO-Your SEO Agent',
    category: 'vibe-coding',
    description: 'plans, executes, and amplifies your product’s reach – from keyword research and content intent to structured data.',
    thumbnailUrl: '/seobo-thumbnail.png',
    slug: 'seobo-your-seo-agent',
  },
  // {
  //   id: 5,
  //   title: 'Healthcare Portal Study',
  //   category: 'ux-case-studies',
  //   description: 'User research and design for patient portal',
  //   thumbnailUrl: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=600',
  //   slug: 'healthcare-portal-study',
  // },
  {
    id: 6,
    title: 'Customer Relationship Management',
    category: 'ux-case-studies',
    description: 'Track leads, nurture customer relationships, and boost sales with ease.',
    thumbnailUrl: '/crm-thumbnail.png',
    slug: 'customer-relationship-management',
  },
  {
    id: 7,
    title: 'Invoice Management System',
    category: 'ux-case-studies',
    description: 'Simplify billing, track payments, and automate financial workflows seamlessly.',
    thumbnailUrl: '/invoice-thumbnail.png',
    slug: 'invoice-management-system',
  },
  {
    id: 7,
    title: 'Kampkode social kit',
    category: 'designs',
    description: 'Simplify billing, track payments, and automate financial workflows seamlessly.',
    thumbnailUrl: '/kampkode-thumbnail.png',
    slug: 'kampkode-social-kit',
  },
];
